/*
 * Macros visible to compiled Merry programs (via the wrapper
 * generated by data/merry::create).
 *
 * Lifted from SkotOS /usr/SkotOS/include/merrynode.h. SkotOS-only
 * game-content includes dropped (client.h, SAM.h, base/preps.h,
 * base/living.h, base/bulk.h) per LM-2 sub-decisions.
 */

# include <status.h>

# define Error(e)		error(e)
